use chrono::{DateTime, Local, NaiveDateTime};

enum Weather {
    Blizzards,
    ClearSkies,
    Clouds,
    DustStorms,
    FairSkies,
    Fog,
    Gales,
    Gloom,
    HeatWaves,
    Rain,
    Showers,
    Snow,
    Thunder,
    Thunderstorms,
    UmbralStatic,
    UmbralWind,
    Wind,
}

impl Weather {
    fn as_str(&self) -> &'static str {
        match self {
            Weather::Blizzards => "blizzards",
            Weather::ClearSkies => "clearSkies",
            Weather::Clouds => "clouds",
            Weather::DustStorms => "dustStorms",
            Weather::FairSkies => "fairSkies",
            Weather::Fog => "fog",
            Weather::Gales => "gales",
            Weather::Gloom => "gloom",
            Weather::HeatWaves => "heatWaves",
            Weather::Rain => "rain",
            Weather::Showers => "showers",
            Weather::Snow => "snow",
            Weather::Thunder => "thunder",
            Weather::Thunderstorms => "thunderstorms",
            Weather::UmbralStatic => "umbralStatic",
            Weather::UmbralWind => "umbralWind",
            Weather::Wind => "wind",
        }
    }
}

enum Zones {
    AmhAraeng,
    AzysLla,
    BozjanSouthernFront,
    CentralShroud,
    CentralThanalan,
    CoerthasCentralHighlands,
    CoerthasWesternHighlands,
    EastShroud,
    EasternLaNoscea,
    EasternThanalan,
    Eulmore,
    EurekaAnemos,
    EurekaHydatos,
    EurekaPagos,
    EurekaPyros,
    Gridania,
    Idyllshire,
    IlMheg,
    Ishgard,
    Kholusia,
    Kugane,
    Lakeland,
    LimsaLominsa,
    LowerLaNoscea,
    MiddleLaNoscea,
    Mist,
    MorDhona,
    NorthShroud,
    NorthernThanalan,
    OuterLaNoscea,
    RhalgrsReach,
    Shirogane,
    SouthShroud,
    SouthernThanalan,
    TheAzimSteppe,
    TheChurningMists,
    TheCrystarium,
    TheDiadem,
    TheDravanianForelands,
    TheDravanianHinterlands,
    TheFringes,
    TheGoblet,
    TheLavenderBeds,
    TheLochs,
    ThePeaks,
    TheRaktikaGreatwood,
    TheRubySea,
    TheSeaOfClouds,
    TheTempest,
    Uldah,
    UpperLaNoscea,
    WesternLaNoscea,
    WesternThanalan,
    WolvesDenPier,
    Yanxia,
    Zadnor,
}

impl Zones {
    fn as_str(&self) -> &'static str {
        match self {
            Zones::AmhAraeng => "amhAraeng",
            Zones::AzysLla => "azysLla",
            Zones::BozjanSouthernFront => "bozjanSouthernFront",
            Zones::CentralShroud => "centralShroud",
            Zones::CentralThanalan => "centralThanalan",
            Zones::CoerthasCentralHighlands => "coerthasCentralHighlands",
            Zones::CoerthasWesternHighlands => "coerthasWesternHighlands",
            Zones::EastShroud => "eastShroud",
            Zones::EasternLaNoscea => "easternLaNoscea",
            Zones::EasternThanalan => "easternThanalan",
            Zones::Eulmore => "eulmore",
            Zones::EurekaAnemos => "eurekaAnemos",
            Zones::EurekaHydatos => "eurekaHydatos",
            Zones::EurekaPagos => "eurekaPagos",
            Zones::EurekaPyros => "eurekaPyros",
            Zones::Gridania => "gridania",
            Zones::Idyllshire => "idyllshire",
            Zones::IlMheg => "ilMheg",
            Zones::Ishgard => "ishgard",
            Zones::Kholusia => "kholusia",
            Zones::Kugane => "kugane",
            Zones::Lakeland => "lakeland",
            Zones::LimsaLominsa => "limsaLominsa",
            Zones::LowerLaNoscea => "lowerLaNoscea",
            Zones::MiddleLaNoscea => "middleLaNoscea",
            Zones::Mist => "mist",
            Zones::MorDhona => "morDhona",
            Zones::NorthShroud => "northShroud",
            Zones::NorthernThanalan => "northernThanalan",
            Zones::OuterLaNoscea => "outerLaNoscea",
            Zones::RhalgrsReach => "rhalgrsReach",
            Zones::Shirogane => "shirogane",
            Zones::SouthShroud => "southShroud",
            Zones::SouthernThanalan => "southernThanalan",
            Zones::TheAzimSteppe => "theAzimSteppe",
            Zones::TheChurningMists => "theChurningMists",
            Zones::TheCrystarium => "theCrystarium",
            Zones::TheDiadem => "theDiadem",
            Zones::TheDravanianForelands => "theDravanianForelands",
            Zones::TheDravanianHinterlands => "theDravanianHinterlands",
            Zones::TheFringes => "theFringes",
            Zones::TheGoblet => "theGoblet",
            Zones::TheLavenderBeds => "theLavenderBeds",
            Zones::TheLochs => "theLochs",
            Zones::ThePeaks => "thePeaks",
            Zones::TheRaktikaGreatwood => "theRaktikaGreatwood",
            Zones::TheRubySea => "theRubySea",
            Zones::TheSeaOfClouds => "theSeaOfClouds",
            Zones::TheTempest => "theTempest",
            Zones::Uldah => "uldah",
            Zones::UpperLaNoscea => "upperLaNoscea",
            Zones::WesternLaNoscea => "westernLaNoscea",
            Zones::WesternThanalan => "westernThanalan",
            Zones::WolvesDenPier => "wolvesDenPier",
            Zones::Yanxia => "yanxia",
            Zones::Zadnor => "zadnor",
        }
    }
}

pub fn calculate_weather(date: NaiveDateTime) -> i8 {
    let unix_time = date.timestamp();
}